[workspace]
name = "edgeai_robot_ws"
channels = [
  "https://prefix.dev/conda-forge",
  "https://prefix.dev/robostack-jazzy",
]
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
# ROS 2 Jazzy
ros2-distro-mutex = ">=0.13,<0.14"
ros-jazzy-ros2cli = "*"
ros-jazzy-ros2run = "*"
ros-jazzy-ros2launch = "*"
ros-jazzy-robot-state-publisher = "*"
ros-jazzy-joint-state-publisher = "*"
ros-jazzy-xacro = "*"
ros-jazzy-rviz2 = "*"
ros-jazzy-tf2-ros = "*"
ros-jazzy-ros-gz = ">=1.0.18,<2"
ros-jazzy-tf2-tools = ">=0.36.18,<0.37"
ros-dev-tools = ">=1.0.2,<2"

[activation.env]
RMW_IMPLEMENTATION = "rmw_cyclonedds_cpp"
ROS_AUTOMATIC_DISCOVERY_RANGE = "SUBNET"
ROS_DOMAIN_ID = "0"
